"""add skill contributions

Revision ID: 017
Revises: 016
Create Date: 2026-05-06 21:08:05.082274
"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers
revision: str = '017'
down_revision: Union[str, None] = '016'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skill_contributions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('skill_id', sa.UUID(), nullable=True),
    sa.Column('contributor_id', sa.UUID(), nullable=False),
    sa.Column('base_version', sa.Integer(), nullable=True, comment='Version number this contribution was forked from. Null for new skills.'),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('storage_path', sa.String(length=1000), nullable=True, comment="MinIO prefix for this contribution's files, e.g. 'contributions/{id}/'"),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contributor_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_skill_contributions_contributor_id', 'skill_contributions', ['contributor_id'], unique=False)
    op.create_index(op.f('ix_skill_contributions_status'), 'skill_contributions', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_skill_contributions_status'), table_name='skill_contributions')
    op.drop_index('ix_skill_contributions_contributor_id', table_name='skill_contributions')
    op.drop_table('skill_contributions')
    # ### end Alembic commands ###
